version: "3.8"
services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: 128M
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SCRIPT_NAME=/todo-mvc-flask
      - LOG_LEVEL=INFO
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres
  db:
    image: postgres:16
    restart: always
    user: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    expose:
      - "5432"
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
