
# create IAM policy to allow the k8s service account (KSA) to access the 
# GCP service account (GSA) granted gcp services, such as secret manager.
# 
# gcloud iam service-accounts add-iam-policy-binding $GCP_SERVICE_ACCOUNT \
#   --role roles/iam.workloadIdentityUser \
#   --member "serviceAccount:$PROJECT_ID.svc.id.goog[$KSA_NAMESPACE/$KSA_NAME]"
#
# NOTE: this has to be done BEFORE creating the k8s service account below.

---
# Kubernetes Service Account for the application namespace
# Note the annotation to link the KSA to the GSA for workload identity
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-api-sa
  namespace: todo-api
  annotations:
    iam.gke.io/gcp-service-account: node-sa@poc-data-platform-289915.iam.gserviceaccount.com
