name: CICD
on:
  push:
    branches:
      - main
env:
  DOCKER_BUILDKIT: 1
jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.11"
      - name: Install dependencies
        run: pip install uv && uv pip install --system ruff
      - name: Check format and lint rules
        run: uv run ruff check
  # build with manual push
  # build-and-push:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Cancel Previous Runs
  #       uses: styfle/cancel-workflow-action@0.12.0
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Build
  #       run: |
  #         # docker build --progress=plain --tag ${{ github.repository }}:${{ github.sha }} .
  #         docker build --progress=plain --tag ikalidocker/example-todo-fastapi:${{ github.sha }} .
  #     - name: Push
  #       run: |
  #         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #         # docker push ${{ github.repository }}:${{ github.sha }}
  #         docker push ikalidocker/example-todo-fastapi:${{ github.sha }}
  # use docker buildx and docker/build-push-action for multi-arch build
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ikalidocker/example-todo-fastapi:${{ github.sha }}
            ikalidocker/example-todo-fastapi:latest
          labels: |
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}
